var registrosJson=[
//Entradas
{"id": 1, "firstName": "Chicken Wings", "image": "", "lastName": "Deliciosas alitas de pollo listas para darle placer a su paladar.", "title":"Hamburguesas", "managerId": 0, "city":"", "precio":"450", "officePhone":"212-999-8887", "email":""},
{"id": 2, "firstName": "Focaccia Con Napoli", "image": "", "lastName": "E", "title":"Pastas", "managerId": 1, "city":"", "precio":"350", "officePhone":"570-123-4567", "email":""},
{"id": 3, "firstName": "Montaditos Zulianos", "image": "", "lastName": "n", "title":"Entradas", "managerId": 2, "city":"", "precio":"450", "officePhone":"570-843-8963", "email":""},
//Pollos
{"id": 4, "firstName": "Papitas de Carne", "image": "", "lastName": "a", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"550", "officePhone":"570-968-5741", "email":""},
{"id": 5, "firstName": "Chicken Fingers", "image": "", "lastName": "Divina salsa nápoli con tocineta y peperoncito.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"550", "officePhone":"570-968-5741", "email":""},
//Carnes
{"id": 6, "firstName": "Tequeños", "image": "", "lastName": "o", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"550", "officePhone":"570-968-5741", "email":""},
{"id": 7, "firstName": "Chili", "image": "", "lastName": "Ricos trocitos de carne de res salteadas con cebolla, pimentón y salsa napoli con un toque de picante.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"480", "officePhone":"570-968-5741", "email":""},
//Ensaladas
{"id": 8, "firstName": "Bufalo wings", "image": "", "lastName": "Deliciosa salsa de crema de leche, champiñones y cebolla, salteadas con un toque de vino blanco.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"400", "officePhone":"570-968-5741", "email":""},
{"id": 9, "firstName": "Crepes Ajo Porro", "image": "", "lastName": "a", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"500", "officePhone":"570-968-5741", "email":""},
//Postres
{"id": 10, "firstName": "Crepes Bibas", "image": "", "lastName": "Tomates frescos, suave mozzarella, albahaca fresca y como aderezo aceite de oliva, sal y pimienta.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"550", "officePhone":"570-968-5741", "email":""},
{"id": 11, "firstName": "Crema de Auyama", "image": "", "lastName": "Ésta es la más tradicional de las salsas, está hecha con tocineta, crema de leche y divino parmesano.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"250", "officePhone":"570-968-5741", "email":""},
{"id": 12, "firstName": "Crema de Apio", "image": "", "lastName": "k", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"250", "officePhone":"570-968-5741", "email":""},
{"id": 13, "firstName": "Sopa de Pollo", "image": "", "lastName": "j", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"250", "officePhone":"570-968-5741", "email":""},
{"id": 14, "firstName": "Ensalada Cesar con Pollo", "image": "", "lastName": "Delicioso chili de carne, pico de gallo y queso fundido, acompañado de crujientes nachos.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"750", "officePhone":"570-968-5741", "email":""},
{"id": 15, "firstName": "Ensalada Capresa", "image": "", "lastName": "Suculento consomé de pollo, crema de leche, queso y maíz.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"600", "officePhone":"570-968-5741", "email":""},
{"id": 16, "firstName": "Ensalada Primavera", "image": "", "lastName": "Pollo empanizado, gratinado con salsa napoli,  mozzarella y parmesano.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"700", "officePhone":"570-968-5741", "email":""},
{"id": 17, "firstName": "Pasta 4 Queso", "image": "", "lastName": "Exquisitas tortillas rellenas con deliciosa crema de ajo porros, gratinadas con bechamel y parmesano.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"400", "officePhone":"570-968-5741", "email":""},
{"id": 18, "firstName": "Pasta Bologna", "image": "", "lastName": "Exquisitas tortillas rellenas con deliciosa crema, maíz y pollo, gratinadas con bechamel y parmesano.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"550", "officePhone":"570-968-5741", "email":""},
{"id": 19, "firstName": "Pasta Fungi", "image": "", "lastName": "Carne de res envuelta en tocineta bañado en salsa de vino tinto con champiñones y cebolla salteadas.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"600", "officePhone":"570-968-5741", "email":""},
{"id": 20, "firstName": "Pasta Carbonara", "image": "", "lastName": "Esta es la clásica hamburguesa con nuestra jugosa carne al grill, dentro del suave y delicioso pan.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"500", "officePhone":"570-968-5741", "email":""},
{"id": 21, "firstName": "Fileto Pomodoro", "image": "", "lastName": "La más ligera de la casa con un juegoso filete de pechuga a la plancha, dentro del suave y delicioso.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"500", "officePhone":"570-968-5741", "email":""},
{"id": 22, "firstName": "Matricciana", "image": "", "lastName": "Carne de res, en crema de leche  y cuatro tipos de quesos. termino de su preferencia.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"600", "officePhone":"570-968-5741", "email":""},
{"id": 23, "firstName": "Pasticho", "image": "", "lastName": "P", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"550", "officePhone":"570-968-5741", "email":""},
{"id": 24, "firstName": "Cartioccio de Lomito", "image": "", "lastName": "P", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"900", "officePhone":"570-968-5741", "email":""},
{"id": 25, "firstName": "Cartioccio de Pollo", "image": "", "lastName": "Lomito empanizado, gratinado con queso mozzarella, salsa napoli y queso parmesano.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"900", "officePhone":"570-968-5741", "email":""},
{"id": 26, "firstName": "Lomito Bibas", "image": "", "lastName": "ñ", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"900", "officePhone":"570-968-5741", "email":""},
{"id": 27, "firstName": "Parmesana de Lomito", "image": "", "lastName": "400 grs, de jugosos trozos de carne/pollo o ambos al grill, acompañados de chorizo, patacón y queso.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"800", "officePhone":"570-968-5741", "email":""},
{"id": 28, "firstName": "Pollo Capresa", "image": "", "lastName": "Filet de pollo en crema de leche, champiñón y cebolla salteados con un toque de vino blanco.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"750", "officePhone":"570-968-5741", "email":""},
{"id": 29, "firstName": "Cotoleta de Pollo", "image": "", "lastName": "h", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"700", "officePhone":"570-968-5741", "email":""},
{"id": 30, "firstName": "Parrilla de Carne", "image": "", "lastName": "Filet de pollo en crema de leche con cuatro tipos de queso.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"1200", "officePhone":"570-968-5741", "email":""},
{"id": 31, "firstName": "Parrilla de Pollo", "image": "", "lastName": "f", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"1200", "officePhone":"570-968-5741", "email":""},
{"id": 32, "firstName": "Parrilla Especial de Carne", "image": "", "lastName": "x", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"1200", "officePhone":"570-968-5741", "email":""},
{"id": 33, "firstName": "Parrilla Especial de Pollo", "image": "", "lastName": "Suculento consomé de res  y cebollas gratinadas con queso parmesano.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"1200", "officePhone":"570-968-5741", "email":""},
{"id": 34, "firstName": "Parrilla Especial Mixta", "image": "", "lastName": "Todos los días nuestro chef prepara una rica sopa que no podrás  pasarla por alto.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"1200", "officePhone":"570-968-5741", "email":""},
{"id": 35, "firstName": "Parrilla Mixta", "image": "", "lastName": "Carne de res flambeada con brandy y varios tipos de pimienta.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"1200", "officePhone":"570-968-5741", "email":""},
{"id": 36, "firstName": "Hamburguesa de Carne", "image": "", "lastName": "Pan cuadrado con jugoso filete de pechuga, jamón de pierna y queso gouda.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"700", "officePhone":"570-968-5741", "email":""},
{"id": 37, "firstName": "Hamburguesa de Pollo", "image": "", "lastName": "r", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"700", "officePhone":"570-968-5741", "email":""},
{"id": 38, "firstName": "Burguer Papo Carne", "image": "", "lastName": "r", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"750", "officePhone":"570-968-5741", "email":""},
{"id": 39, "firstName": "Burguer Papo de Pollo", "image": "", "lastName": "r", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"750", "officePhone":"570-968-5741", "email":""},
{"id": 40, "firstName": "Pizza Napoli", "image": "", "lastName": "r", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"450", "officePhone":"570-968-5741", "email":""},
{"id": 41, "firstName": "Pizza Jamon", "image": "", "lastName": "r", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"500", "officePhone":"570-968-5741", "email":""},
{"id": 42, "firstName": "Pizza Margarita", "image": "", "lastName": "r", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"550", "officePhone":"570-968-5741", "email":""},
{"id": 43, "firstName": "Pizza Vegetariana", "image": "", "lastName": "r", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"550", "officePhone":"570-968-5741", "email":""},
{"id": 44, "firstName": "Pizza Tocineta", "image": "", "lastName": "r", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"600", "officePhone":"570-968-5741", "email":""},
{"id": 45, "firstName": "Pizza Salami", "image": "", "lastName": "r", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"600", "officePhone":"570-968-5741", "email":""},
{"id": 46, "firstName": "Pizza Peperonni", "image": "", "lastName": "r", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"600", "officePhone":"570-968-5741", "email":""},
];



