var registrosJson=[
{"id": 1, "firstName": "Hamburguesa de Carne", "image": "", "lastName": "Hamburguesa americana de carne con ingredientes frescos listos para degustar.", "title":"Hamburguesas", "managerId": 0, "city":"New York, NY", "cellPhone":"212-999-8888", "officePhone":"212-999-8887", "email":"ryan@dundermifflin.com"},
{"id": 2, "firstName": "Pasta Neudo", "image": "", "lastName": "Pasta de su eleccion con salsa a base de ricos tomates y un toque de especies tradicionales.", "title":"Pastas", "managerId": 1, "city":"Scranton, PA", "cellPhone":"570-865-2536", "officePhone":"570-123-4567", "email":"michael@dundermifflin.com"},
{"id": 3, "firstName": "Nachos", "image": "", "lastName": "Deliciosos nachos tipicos de Mexico con una salsa hecha en casa", "title":"Entradas", "managerId": 2, "city":"Scranton, PA", "cellPhone":"570-865-1158", "officePhone":"570-843-8963", "email":"dwight@dundermifflin.com"},
{"id": 4, "firstName": "Pollo a la Mostaza", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "cellPhone":"570-865-8989", "officePhone":"570-968-5741", "email":"dwight@dundermifflin.com"},
{"id": 4, "firstName": "Nom.", "image": "", "lastName": "Desc.", "title":"cat.", "managerId": 2, "city":"ciud.", "cellPhone":"cell", "officePhone":"cell", "email":"abcd@abcd.com"},
{"id": 4, "firstName": "Papas Supremas", "image": "", "lastName": "DEliciosas papas onduladas, banadas en queso cheddar, tocineta, crunch y cebollin finanmente picadas.", "title":"Entradas", "managerId": 2, "city":"ciud.", "cellPhone":"cell", "officePhone":"cell", "email":"abcd@abcd.com"},
{"id": 4, "firstName": "Cuatro", "image": "", "lastName": "Arepa frita o asadas de carne al carbon con pico de gallo y queso rallado "},
{"id": 4, "firstName": "Furro", "image": "", "lastName": "Arepa frita o asadas de pollo al carbon con pico de gallo y queso rallado "},
{"id": 4, "firstName": "Charrasca", "image": "", "lastName": "Arepa frita o asadas mixta de carne y pollo al carbon con pico de gallo y queso rallado "},
{"id": 4, "firstName": "Cesar con Pollo", "image": "", "lastName": "Pechuga de Pollo grillada, lechuga Romana, Banada con nuestro aderezi cesar y crotones"},
{"id": 4, "firstName": "Cole Slaw", "image": "", "lastName": "Ensalada de repollo blanco y morado con zanahoria rallada y aderezo de mayonesa dulce"},
{"id": 4, "firstName": "Ejecutivo", "image": "", "lastName": "Una proteina con tres contornos de su preferencia acompanado con la crema del dia y un nestea"},
{"id": 4, "firstName": "Sopa", "image": "", "lastName": "Deliciosa Sopa preparada por nuestro chef"},
{"id": 4, "firstName": "Puerto de Maracaibo", "image": "", "lastName": "Nuestra clasica y deliciosa Hamburguesa de carne o pollo cocida al termino de su eleccion acompanada de papas fritas"},
{"id": 4, "firstName": "Vereda del Lago", "image": "", "lastName": "Hamburguesa de carne o pollo cubierta con una deliciosa capa de salsa al pesto con queso mozzarella"},
{"id": 4, "firstName": "Lago de Maracaibo", "image": "", "lastName": "Hamburguesa de carne o pollo cubierta con queso azul tocineta y queso de mano"},
{"id": 4, "firstName": "Relampago del Catatumbo", "image": "", "lastName": "Hamburguesa de carne o pollo cubierta de nuestra salsa BBQ, tocineta, cebolla caramelizada, champinones, y queso de mano"},
{"id": 4, "firstName": "Maracaibos`s grill & BQQ", "image": "", "lastName": "Hamburguesa de 360 grs de carne, Tocineta, Cebolla Caramelizada"},
{"id": 4, "firstName": "Ciudad del Solamada", "image": "", "lastName": "Hamburguesa de carne o pollo, tocineta y queso de mano"},
{"id": 4, "firstName": "Vegetariana", "image": "", "lastName": "Hamburguesa de carne o pollo, tocineta y huevo frito"},
{"id": 4, "firstName": "La grey Zuliana", "image": "", "lastName": "Desc.", "title":"Parrillas", "managerId": 2, "city":"ciud.", "cellPhone":"cell", "officePhone":"cell", "email":"abcd@abcd.com"},
{"id": 4, "firstName": "El Saladillo", "image": "", "lastName": "Desc.", "title":"Parrillas", "managerId": 2, "city":"ciud.", "cellPhone":"cell", "officePhone":"cell", "email":"abcd@abcd.com"},
{"id": 4, "firstName": "18 de Noviembre", "image": "", "lastName": "Desc.", "title":"Parrillas", "managerId": 2, "city":"ciud.", "cellPhone":"cell", "officePhone":"cell", "email":"abcd@abcd.com"},
{"id": 4, "firstName": "Tradicional", "image": "", "lastName": "Desc.", "title":"Panes", "managerId": 2, "city":"ciud.", "cellPhone":"cell", "officePhone":"cell", "email":"abcd@abcd.com"},
{"id": 4, "firstName": "Americana", "image": "", "lastName": "Desc.", "title":"Panes", "managerId": 2, "city":"ciud.", "cellPhone":"cell", "officePhone":"cell", "email":"abcd@abcd.com"},
{"id": 4, "firstName": "Mexicano", "image": "", "lastName": "Desc.", "title":"Panes", "managerId": 2, "city":"ciud.", "cellPhone":"cell", "officePhone":"cell", "email":"abcd@abcd.com"},
{"id": 4, "firstName": "Nom.", "image": "", "lastName": "Desc.", "title":"cat.", "managerId": 2, "city":"ciud.", "cellPhone":"cell", "officePhone":"cell", "email":"abcd@abcd.com"},
{"id": 4, "firstName": "Nom.", "image": "", "lastName": "Desc.", "title":"cat.", "managerId": 2, "city":"ciud.", "cellPhone":"cell", "officePhone":"cell", "email":"abcd@abcd.com"},
{"id": 4, "firstName": "Nom.", "image": "", "lastName": "Desc.", "title":"cat.", "managerId": 2, "city":"ciud.", "cellPhone":"cell", "officePhone":"cell", "email":"abcd@abcd.com"},
{"id": 4, "firstName": "Nom.", "image": "", "lastName": "Desc.", "title":"cat.", "managerId": 2, "city":"ciud.", "cellPhone":"cell", "officePhone":"cell", "email":"abcd@abcd.com"},
{"id": 4, "firstName": "Nom.", "image": "", "lastName": "Desc.", "title":"cat.", "managerId": 2, "city":"ciud.", "cellPhone":"cell", "officePhone":"cell", "email":"abcd@abcd.com"},


];

