var registrosJson=[
//Entradas
{"id": 1, "firstName": "Hamburguesa de Carne", "image": "", "lastName": "Hamburguesa americana de carne con ingredientes frescos listos para degustar.", "title":"Hamburguesas", "managerId": 0, "city":"", "precio":"350", "officePhone":"212-999-8887", "email":""},
{"id": 2, "firstName": "Pasta Neudo", "image": "", "lastName": "Pasta de su eleccion con salsa a base de ricos tomates y un toque de especies tradicionales.", "title":"Pastas", "managerId": 1, "city":"", "precio":"400", "officePhone":"570-123-4567", "email":""},
{"id": 3, "firstName": "Nachos", "image": "", "lastName": "Deliciosos nachos tipicos de Mexico con una salsa hecha en casa", "title":"Entradas", "managerId": 2, "city":"", "precio":"630", "officePhone":"570-843-8963", "email":""},
//Pollos
{"id": 4, "firstName": "Pollo a la Mostaza", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"270", "officePhone":"570-968-5741", "email":""},
{"id": 5, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"890", "officePhone":"570-968-5741", "email":""},
//Carnes
{"id": 6, "firstName": "Pollo a la Mostaza", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"490", "officePhone":"570-968-5741", "email":""},
{"id": 7, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"540", "officePhone":"570-968-5741", "email":""},
//Ensaladas
{"id": 8, "firstName": "Pollo a la Mostaza", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"380", "officePhone":"570-968-5741", "email":""},
{"id": 9, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"330", "officePhone":"570-968-5741", "email":""},
//Postres
{"id": 10, "firstName": "Pollo a la Mostaza", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"520", "officePhone":"570-968-5741", "email":""},
{"id": 11, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 12, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 13, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 14, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 15, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 16, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 17, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 18, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 19, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 20, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 21, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 22, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 23, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 24, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 25, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 26, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 27, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 28, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 29, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 30, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 31, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 32, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 33, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 34, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 35, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 36, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},
{"id": 37, "firstName": "proximo", "image": "", "lastName": "Pollo preparado con una espectacular salsa con un toque de mostaza.", "title":"Aves", "managerId": 2, "city":"Scranton, PA", "precio":"180", "officePhone":"570-968-5741", "email":""},

];

